name: "First Workflow file"
on: 
    push: 
        branches:
            - main
            - test
    pull_request:
        branches:
            - main
    schedule:
        - cron: "0 10 * * 2,4"

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - run: npm init -y
            - run: npm install

    on-pull_request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - run: echo "On Pull Request"
            - run: echo "You did good"
            - run: echo "You did even more good"
    on-schedule:
        if: github.event_name == 'schedule'
        runs-on: ubuntu-latest
        steps:
            - run: echo "Set to run on Tuesdays and Thrusdays"