name: "First Workflow file"
on: 
    push: 
        branches:
            - main
            - test
    pull_request:
        branches:
            - main

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - run: npm init -y

    on-pull-request:
        if: github.event_name == 'pull-request'
        runs-on: ubuntu-latest
        steps:
            - run: echo "On Pull Request"
            - run: echo "You did good"
            - run: echo "You did even more good"