name: "First Workflow file"
on: push

jobs:
    Hello-all:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"
    
    on-push:
        runs-on: ubuntu-latest
        steps:
            - run: npm init -y
            - run: npm install